apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: graphql-api-service-pipeline
description: Deployment pipeline for GraphQl Api service for Test E-Papers
serialPipeline:
  stages:
    - targetId: test
      profiles: [test]
      strategy:
        standard:
          verify: false
    - targetId: prod
      profiles: [prod]
      strategy:
        standard:
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: Test environment
run:
  location: projects/testepapers/locations/asia-south2
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Production environment
requireApproval: true  # ⭐ Manual approval required
run:
  location: projects/testepapers/locations/asia-south2